appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c34442ed1578b0700314af3
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: ks5WO2jpJaLhfb6laAKZbARVpdsUtQiyTSJAGPr2+UrCAkj1nkd+muEERQ0Eucyzzx3Evvkkc6pxVb+0QnHOZo/p5ZMjdlm5+tVxRAxg8w43TSZUZIBrILH1t9DK6GGcEQFxtXrzhl3E9pBEL/P1t8c7Nl6hoLfMCw1BTvcWO4Af/OEU6qCoS/HwZT5LZt3t39ciuTBwMyD6ZfQDITCV2RKPsu2uvkjfjBzyNXZ1QpxQP2qy4jxCaZzBVfFJXLYWJFd0QJXZLg5JgUKjsp8efESURayzYc9R1TmcnYgfZRiTE/4k1xKvcOrF0d8M0GTSYrISXy9HJDB6yy7Qe6MJEPMsUDhSXzK+LFYOctemqHYcgSYo2QrUkwlz1jYZbLt9ElRed1/chW8OuLUBguiDKsBbOmOH9XrelzENt3jyLFypVlw7K58MVdiu4mjwLsUgkkstEQELQFpfch6zLk6VrMIkLFBjAqkmpnvHOF43TkS3LJK/h79tDeQGME+C1Y9Obrh6b9jrQX9OcRp4xfRMYfUrYkjIkfsGGQH7e/3Olb/CeFviGezeSZesC5n6hXhcd5jqdxGsqKy3FKN/9il0y/9ST9YCkOZ/dI+AKQ50qXJ+1IspiGfyF7JO9FuHQfF8ZyydTVtJKaED+u0AnEE4D7q5SlhwOr4I2TfNeuWj5lM=}
